/**
 * Icon re-exports from @ant-design/icons.
 *
 * Short-term strategy: re-export to give frontend a single import source.
 * Long-term: gradually replace with built-in SVG Icon components.
 */
export {
  // ─── High frequency (5+ files) ───
  InfoCircleOutlined,
  ArrowDownOutlined,
  ArrowUpOutlined,
  RiseOutlined,
  ThunderboltOutlined,

  // ─── Medium frequency (3-4 files) ───
  CalendarOutlined,
  BarChartOutlined,
  BulbOutlined,
  RocketOutlined,
  RightOutlined,
  DownOutlined,
  NodeExpandOutlined,

  // ─── Low frequency (1-2 files) ───
  FallOutlined,
  LockOutlined,
  UserOutlined,
  CheckCircleOutlined,
  DownloadOutlined,
  CrownOutlined,
  SmileOutlined,
  MedicineBoxOutlined,
  GlobalOutlined,
  SafetyCertificateOutlined,
  SearchOutlined,
  FilterOutlined,
  MoreOutlined,
  ThunderboltFilled,
  CaretUpOutlined,
  CaretDownOutlined,
  FileTextOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  CloseOutlined,
  PushpinOutlined,
  MessageOutlined,
  MinusOutlined,
  SolutionOutlined,
  InfoCircleFilled,
  AimOutlined,
  QuestionCircleOutlined,
  TeamOutlined,
  UpOutlined,
  AppstoreOutlined,
  AlertOutlined,
  ExperimentOutlined,
  BankOutlined,
  BellOutlined,
  ClockCircleOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DislikeOutlined,
  DollarOutlined,
  EditOutlined,
  EnvironmentOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  FileSearchOutlined,
  FireOutlined,
  HeartOutlined,
  HomeOutlined,
  StopOutlined,
  CloudServerOutlined,
  WarningOutlined,
  SettingOutlined,
  MenuOutlined,
  LineChartOutlined,
  LogoutOutlined,
  NodeIndexOutlined,
  PhoneOutlined,
  PlusOutlined,
  SafetyOutlined,
  StarOutlined,
  SwapOutlined,
  UserAddOutlined,
  WifiOutlined,
  LeftOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
} from '@ant-design/icons';
